#redis: &redis
#  adapter: redis
#  url: redis://localhost:6379/1

#production: *redis
#development: *redis
#test: *redis


 production: 
    adapter: async
 development: 
    adapter: async
 test:
    adapter: async 